### Lab 2
## Linear Algebra in Data Science

1. Create two 2x2 matrices and perform the following matrix operations using numpy:


a. Addition
b. Subtraction
c. Scalar Multiplication
d. Matrix Multiplication
e. Transpose
f. Determinant
g. Inverse

In [1]:
import numpy as np 

#init a matirx
a = np.array([ [13, 14], [17, 19] ])
a

array([[13, 14],
       [17, 19]])

In [2]:
#init b matrix
b = np.array([ [3, 4], [5, 6] ])
b

array([[3, 4],
       [5, 6]])

In [3]:
#adding two matrices
a + b

array([[16, 18],
       [22, 25]])

In [4]:
#subtracting two matrices
a - b

array([[10, 10],
       [12, 13]])

In [5]:
#scalar multiplication
print("scalar mult of b with 4")
print(3 * a)
print("scalar mult of b with 4")
print(4 * b)

scalar mult of b with 4
[[39 42]
 [51 57]]
scalar mult of b with 4
[[12 16]
 [20 24]]


In [6]:
#matrix multiplication
a @ b

array([[109, 136],
       [146, 182]])

In [7]:
#transpose a
print("Transpose of matrix a")
print(np.transpose(a))

#transpose b
print("Transpose of matrix a")
print(np.transpose(b))

Transpose of matrix a
[[13 17]
 [14 19]]
Transpose of matrix a
[[3 5]
 [4 6]]


In [8]:
#determinant a
print("Determinat of matrix a")
print(np.linalg.det(a))
#determinant b
print("Determinat of matrix b")
print(np.linalg.det(b))

Determinat of matrix a
8.99999999999997
Determinat of matrix b
-1.9999999999999971


In [9]:
#inverse of a
print("Inverse of matrix a")
print(np.linalg.inv(a))
#inverse b
print("Inverse of matrix b")
print(np.linalg.inv(b))

Inverse of matrix a
[[ 2.11111111 -1.55555556]
 [-1.88888889  1.44444444]]
Inverse of matrix b
[[-3.   2. ]
 [ 2.5 -1.5]]


2. Solve the following equations using matrices (vectorized implementation):   
a. z = 3a + 4b + 5c where, a=2, b=3, c=1   
b. z = 1 + 4p + 10q - 7r where p=-1, q=3, r=2


In [10]:
#equation a soln

#coefficient matrix
c = np.array([3, 4, 5])
#variable matrix
d = np.array([[2], [3], [1]])

c@d

array([23])

In [11]:
#equation b soln

#coefficient matrix
e = np.array([1, 4, 10, -7])
#variable matrix
f = np.array([[1], [-1], [3], [2]])

e@f

array([13])

3. Create an array of size 100 with values ranging from 1 to 50. Then, use the following formula to scale the values between 0 to 1.   
X = (X - Xmin) / (Xmax - Xmin)


In [12]:
z = np.linspace(1, 50, 100)
x = (z - z.min()) / (z.max() - z.min())
x

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

4. Collect the age information from the lab groupmates via. google form then, compute
mean, median, mode, and standard deviation.      Use pandas to read the Excel file and
numpy for further calculation. Normalize the age of your groupmates using the
following formula:    
X = (X - Xmean) / Xstd

In [13]:
import pandas as pd

df = pd.read_csv("age.csv")

df.columns

Index(['Timestamp', 'Name', 'How long have you existed?'], dtype='object')

In [14]:
df = df.rename(columns = {"How long have you existed?": "age"})
df["age"] = df["age"].astype(int)

ageMean = df["age"].mean()
ageSD = df["age"].std()

df["normalized_age"] = (df["age"] - ageMean) / ageSD

for age in df["normalized_age"]:
    print(age)

-2.4626394988782683
1.0103136405654423
0.31572301267670005
0.31572301267670005
0.31572301267670005
1.0103136405654423
-0.37886761521204204
-0.37886761521204204
-0.37886761521204204
-0.37886761521204204
1.0103136405654423


5. Contemplate the difference between scaling and normalization techniques that are
used in tasks 3 and 4

>ANSWER:<br><br>
In task 3, the operation <b>( X = (X - Xmin) / (Xmax - Xmin) )</b> scales the data to a range of [0, 1]. This operation makes the smallest value 0 and the largest value 1. Scaling in a range specific transformation ensures the data fits that specified rangee. This is commonly used for machine learning algorithms sensitive to range of input. The relative relationships between the data points is preserved.<br>
In task 4, the operation <b>( X = (X - Xmean) / Xstd )</b> standardizes the data by centering it around a mean of 0 and scaling it based on the standard deviation. This operation produces data with a mean of 0 and a standard deviation of 1. This is commonly used when data follows or approximately follows a normal distribuition.<br>
<br>While scaling is more about transforming the data into a defined range for special use in magnitude sensitive algorithms, like the gradient descent.<br>
Normalization standardizes the data such that features with different units or distribuitions can be comparable. For example, in medical records, non-normalized data might value features with higher numeric ranges like weight over others, potentially skewing analysis/predictions.